### ISSUE TITLE
Logging Package

### ISSUE THREAD

**Issue by 0x19** [golanghr/platform#1]
I would definitely not like that we start with new logging system that will do what is already there available on golang community. I do feel that https://github.com/Sirupsen/logrus is good fit and therefore I'll build alpha with it. It will be just small wrapper. Nothing else from start so we can easily change/improve it when and if we need to.

**Comment by 0x19** [comment]
@MatejB you said to add your  https://github.com/MatejB/reactLog as Formatter :)

We should add for next milestone to figure out how to do write one to many formatters.

**Comment by matejb** [comment]
It can't be a formatter as it is middleware.
Only exposure of SetOutput function was needed, added pull request https://github.com/golanghr/platform/pull/2
