### ISSUE TITLE
logging package error on remaster branch

### ISSUE THREAD

**Issue by matejb** [golanghr/platform#4]
Have this errors when I try `go test`:
- ../../../go/src/github.com/golanghr/platform/logging/logging.go:19: embedded type cannot be a pointer to interface
- ../../../go/src/github.com/golanghr/platform/logging/logging.go:30: opts.Exists undefined (type *options.Options is pointer to interface, not interface)
- ../../../go/src/github.com/golanghr/platform/logging/logging.go:31: opts.Get undefined (type *options.Options is pointer to interface, not interface)
- ../../../go/src/github.com/golanghr/platform/logging/logging.go:43: opts.Exists undefined (type *options.Options is pointer to interface, not interface)
- ../../../go/src/github.com/golanghr/platform/logging/logging.go:44: opts.Get undefined (type *options.Options is pointer to interface, not interface)

**Comment by 0x19** [comment]
Hey @MatejB :)

Should be fixed now! 

```
go test
.
1 assertion thus far

.
2 assertions thus far

.
3 assertions thus far

.
4 assertions thus far

..
6 assertions thus far

..
8 assertions thus far

.
9 assertions thus far

x
Failures:

  * /Users/0x19/gocode/src/github.com/golanghr/platform/logging/logging_test.go 
  Line 91:
  Expected '' to contain substring 'This is normal log' (but it didn't)!


10 assertions thus far

x
Failures:

  * /Users/0x19/gocode/src/github.com/golanghr/platform/logging/logging_test.go 
  Line 95:
  Expected '' to contain substring 'This is log that concers user ID 107 with important data' (but it didn't)!


11 assertions thus far

--- FAIL: TestMiddlewareIntegration (0.00s)
FAIL
exit status 1
FAIL    github.com/golanghr/platform/logging    0.008s
```
